apiVersion: apps/v1
kind: Deployment
metadata:
  name: joueur-frontend
  namespace: joueur-rc
spec:
  selector:
    matchLabels:
      app: joueur-frontend
  template:
    metadata:
      labels:
        app: joueur-frontend
    spec:
      containers:
      - name: joueur-frontend
        image: "manishshivanna/joueur-frontend:rc-5-4bc7f9b" 
        resources:
          limits:
            memory: "2048Mi"
            cpu: "1000m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: joueur-frontend
  namespace: joueur-rc
spec:
  selector:
    app: joueur-frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: NodePort
