apiVersion: apps/v1
kind: Deployment
metadata:
  name: joueur-frontend
  namespace: joueur-rc
spec:
  selector:
    matchLabels:
      app: joueur-frontend
  template:
    metadata:
      labels:
        app: joueur-frontend
    spec:
      containers:
      - name: joueur-frontend
        image: manishshivanna/joueur-frontend:rc-10-a317f3e 
        resources:
          limits:
            memory: 275Mi
            cpu: 2
          requests:
            memory: 50Mi
            cpu: 1
        ports:
        - containerPort: 3000
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 90
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 90
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: joueur-frontend
  namespace: joueur-rc
spec:
  selector:
    app: joueur-frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: NodePort
