apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: joueur-backend-claim0
  name: joueur-backend-claim0
  namespace: joueur-rc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
