apiVersion: apps/v1
kind: Deployment
metadata:
  name: joueur-frontend
  namespace: joueur-rc
spec:
  selector:
    matchLabels:
      app: joueur-frontend
  template:
    metadata:
      labels:
        app: joueur-frontend
    spec:
      containers:
      - name: joueur-frontend
        image: manishshivanna/joueur-frontend:rc-3-68d9297 
        resources:
          limits:
            memory: 2048Mi
            cpu: 1
          requests:
            memory: 300Mi
            cpu: 500m
        ports:
        - containerPort: 3000
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 2
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: joueur-frontend
  namespace: joueur-rc
spec:
  selector:
    app: joueur-frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: NodePort
